#!/bin/bash


if [ `id -u` != 0 ];then
        echo ""
        echo -e "\e[31m Failed: Please Run this Script as root\e[0m\n"
        exit 1
fi

####################################################################################

# NFS Server Setup

echo -e "#Deleting and Recreating user accounts.....\n"
for i in user{1..5};do userdel -r $i &>/dev/null;done
declare -A users
users=( ["user1"]=4001 ["user2"]=4002 ["user3"]=4003 )

for user in "${!users[@]}"; do
    uid=${users[$user]}
    sudo useradd -u $uid -m -b /remoteusers $user >/dev/null
    if [ $? -eq 0 ]; then
        echo "User $user with UID $uid created successfully."
    else
        echo "Failed to create user $user with UID $uid."
    fi
done
echo -e "\n#exporting user's home directory.....\n"
echo -e "===========================================\n"
exp_file="/etc/exports"
add_line="/remoteusers *(rw,sync,no_root_squash)"

if ! grep -Fxq "$add_line" "$exp_file"; then
    echo "$add_line" | sudo tee -a "$exp_file" > /dev/null
    exportfs -avr
fi

systemctl restart nfs-server
systemctl enable nfs-server
firewall-cmd --add-service={nfs,rpc-bind,mountd} --permanent &>/dev/null
firewall-cmd --reload &>/dev/null

###########################################################################

# NTP Server Configuration

IP_ADDR=$(ip route get 1 | awk '{print $7; exit}')
NETWORK=$(echo "$IP_ADDR" | cut -d. -f1-3)
SUBNET="$NETWORK.0/24"
CONFIG_FILE="/etc/chrony.conf"

dnf install -y chrony >/dev/null 2>&1
systemctl enable chronyd --now >/dev/null 2>&1

# Allow clients on local network (change subnet as needed)
if ! grep -q '^allow ' "$CONFIG_FILE"; then
    echo "allow $SUBNET" | sudo tee -a "$CONFIG_FILE" >/dev/null 2>&1
fi

# Open NTP port in firewall (UDP 123)
firewall-cmd --add-service={ntp,ptp} --permanent >/dev/null 2>&1
firewall-cmd --add-port={123/udp,323/udp} --permanent >/dev/null 2>&1
firewall-cmd --reload >/dev/null 2>&1

# Enable and restart the service
systemctl restart chronyd >/dev/null 2>&1
